/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoEstudiantes;
import controlador.Controlador_FRM_MantenimientoUsuario;

/**
 *
 * @author Jaki
 */
public class Panel_DatosUsuario extends javax.swing.JPanel {

    /**
     * Creates new form Panel_DatosUsuario
     */
    Controlador_FRM_MantenimientoUsuario controlador;
    
    public Panel_DatosUsuario() 
    {
        initComponents();
       deshabilitarCampos();
        
    }
    
     public void agregarEventos(Controlador_FRM_MantenimientoUsuario controlador)
    {
        this.controlador=controlador;
      
    }
    public String[] devolverInformacion()
    {
        String informacion[]=new String[6];
        informacion[0]=this.jTextCedula.getText();
        informacion[1]=this.jtextNombreCompleto.getText();
        informacion[2]=this.jTextNombreUsuario.getText();
        informacion[3]=this.jPasswordContraseña.getText();
        informacion[4] = this.jPasswordRepetirContraseña.getText();
        informacion[5]=this.jComboTipo.getSelectedItem().toString();
       
        return informacion;
    }
    public String devolverCedula()
    {
        return this.jTextCedula.getText();
    }
    public void mostrarInformacion(String informacion[])
    {
        
        
        this.jTextCedula.setText(informacion[0]);
        this.jtextNombreCompleto.setText(informacion[1]);
        this.jTextNombreUsuario.setText(informacion[2]);
        this.jPasswordContraseña.setText( informacion[3]);
        
    }
    public void habilitarCampos()
    {
         this.jTextCedula.setEnabled(true);
        this.jtextNombreCompleto.setEnabled(true);
        this.jTextNombreUsuario.setEnabled(true);
        this.jPasswordContraseña.setEnabled(true);
        this.jPasswordRepetirContraseña.setEnabled(true);
    }
    public void deshabilitarCampos()
    {
        this.jTextCedula.setEnabled(true);
        this.jTextCedula.setText("");
        this.jtextNombreCompleto.setText("");
        this.jTextNombreUsuario.setText("");
        this.jtextNombreCompleto.setEnabled(false);
        this.jTextNombreUsuario.setEnabled(false);
        this.jPasswordContraseña.setEnabled(false);
        this.jPasswordContraseña.setText("");
        this.jPasswordRepetirContraseña.setEnabled(false);
        this.jPasswordRepetirContraseña.setText("");
    }
    public void habilitarEdicion()
    {
        this.jTextCedula.setEnabled(false);
        this.jtextNombreCompleto.setEnabled(true);
        this.jTextNombreUsuario.setEnabled(true);
        this.jPasswordContraseña.setEnabled(true);
         this.jPasswordRepetirContraseña.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jtextNombreCompleto = new javax.swing.JTextField();
        jTextNombreUsuario = new javax.swing.JTextField();
        jPasswordContraseña = new javax.swing.JPasswordField();
        jPasswordRepetirContraseña = new javax.swing.JPasswordField();
        jComboTipo = new javax.swing.JComboBox();

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("Nombre Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Repetir Contraseña");

        jLabel6.setText("Tipo");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", "Administrador" }));
        jComboTipo.setToolTipText("");
        jComboTipo.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordRepetirContraseña)
                                    .addComponent(jPasswordContraseña)
                                    .addComponent(jTextCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jtextNombreCompleto)
                                    .addComponent(jTextNombreUsuario))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtextNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordContraseña;
    private javax.swing.JPasswordField jPasswordRepetirContraseña;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextNombreUsuario;
    private javax.swing.JTextField jtextNombreCompleto;
    // End of variables declaration//GEN-END:variables
}
